spring:
  application:
    name: spring-google-auth
  datasource:
    url: jdbc:postgresql://localhost:5432/google-auth
    username: username
    password: myp4ssw0rd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# JWT
jwt:
  expires-in: 300
  private:
    key: classpath:config/app.key
  public:
    key: classpath:config/public.key

# Google
google:
  client:
    id: ${GOOGLE_CLIENT_ID}
